# Generated by Django 3.1.5 on 2021-01-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
