# Generated by Django 3.1.5 on 2021-01-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
