# Generated by Django 3.1.5 on 2021-01-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0008_post_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Youtube_link',
        ),
    ]
